# Generated by Django 6.0.1 on 2026-02-11 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
