# Generated by Django 6.0.1 on 2026-01-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allergens',
        ),
        migrations.DeleteModel(
            name='ScanHistory',
        ),
    ]
