# Generated by Django 6.0.1 on 2026-02-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_age_profile_allergies_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
